--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HiroshimaTeam/BlockItemFrame-HiroTeam
build-by-default: true
branches:
- master
projects:
  BlockItemFrame-HiroTeam:
    path: ""
...
